export const VESSEL_INIT = 'VESSEL_INIT';
export const SHOW_LOADING = 'SHOW_LOADING';
export const SET_LAYERS = 'SET_LAYERS';
export const TOGGLE_LAYER_VISIBILITY = 'TOGGLE_LAYER_VISIBILITY';
export const SET_ZOOM = 'SET_ZOOM';
export const SET_CENTER = 'SET_CENTER';
export const SET_TIMELINE_DATES = 'SET_TIMELINE_DATES';
export const SET_WORKSPACE_ID = 'SET_WORKSPACE_ID';
export const DELETE_WORKSPACE_ID = 'DELETE_WORKSPACE_ID';
export const UPDATE_VESSEL_TRANSPARENCY = 'UPDATE_VESSEL_TRANSPARENCY';
export const UPDATE_VESSEL_COLOR = 'UPDATE_VESSEL_COLOR';
export const CHANGE_VESSEL_TRACK_DISPLAY_MODE = 'CHANGE_VESSEL_TRACK_DISPLAY_MODE';

// Search
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';

// User actions
export const GET_USER = 'GET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';
export const TOKEN_SESSION = 'TOKEN_SESSION';

export const GET_RECENT_POSTS = 'GET_RECENT_POSTS';
export const GET_POST_BY_SLUG = 'GET_POST_BY_SLUG';

export const GET_FAQ_ENTRIES = 'GET_FAQ_ENTRIES';
export const GET_ARTICLES_PUBLICATIONS_ENTRIES = 'GET_ARTICLES_PUBLICATIONS_ENTRIES';
export const GET_DEFINITION_ENTRIES = 'GET_DEFINITION_ENTRIES';

// Filters actions
export const UPDATE_FILTERS = 'UPDATE_FILTERS';

// Appearance actions
export const SET_VISIBLE_MENU = 'SET_VISIBLE_MENU';
export const SUPPORT_MODAL_OPEN = 'SUPPORT_MODAL_OPEN';
export const SHARE_MODAL_OPEN = 'SHARE_MODAL_OPEN';
export const SET_SHARE_MODAL_ERROR = 'SET_SHARE_MODAL_ERROR';

// Contact actions
export const FORM_RESPONSE = 'FORM_RESPONSE';

// Vessel info actions
export const SET_VESSEL_DETAILS = 'SET_VESSEL_DETAILS';
export const SET_VESSEL_TRACK = 'SET_VESSEL_TRACK';
export const RESET_VESSEL_DETAILS = 'RESET_VESSEL_DETAILS';
