export const VESSEL_INIT = 'VESSEL_INIT';
export const VESSEL_ZOOM_UPDATE = 'VESSEL_ZOOM_UPDATE';
export const VESSEL_TILE_LOADED = 'VESSEL_TILE_LOADED';
export const SHOW_LOADING = 'SHOW_LOADING';
export const RESET_CACHE = 'RESET_CACHE';
export const ADD_LAYER = 'ADD_LAYER';
